/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex flex-col min-h-screen items-stretch">
        <Navbar />
        <div className="flex-grow bg-zinc-100 dark:bg-zinc-700 text-black dark:text-zinc-50">
          <main className="flex-shrink-0 flex items-center justify-center mt-20">{children}</main>
        </div>
        <div className="flex-shrink-0">
          <Navbar />
        </div>
      </div>
    </>
  );
}
// className={inter.className}