/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex flex-col min-h-screen items-stretch">
        <Navbar />
        <div className="flex-grow bg-gradient-to-r from-[#6c00c8] from-10% to-[#19d6e1] to-98% ">
          <main className="flex-shrink-0 flex items-center justify-center mt-20">
            {children}
          </main>
        </div>
        <div className="flex-shrink-0">
          <Navbar />
        </div>
      </div>
    </>
  );
}
// className={inter.className}