/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/m29S5Iia7xt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/src/app/components/ui/avatar"
import Link from "next/link"

export default function Profile() {
  return (
    <>
      <div className="flex items-center gap-4 p-6 bg-gray-100 dark:bg-gray-800 rounded-lg">
        <Avatar className="h-16 w-16">
          <AvatarImage
            alt="@jaredpalmer"
            src="/placeholder-avatar.jpghttps://images.unsplash.com/photo-1492633423870-43d1cd2775eb?&w=128&h=128&dpr=2&q=80"
          />
          <AvatarFallback>JP</AvatarFallback>
        </Avatar>
        {/* <FaCircleUser className="h-12 w-12 text-gray-500 dark:text-gray-400" /> */}
        <div className="space-y-1">
          <h3 className="text-xl font-semibold">Welcome back, Jared!</h3>
          <p className="text-gray-500 dark:text-gray-400">
            Let's dive into your writing journey.
          </p>
        </div>
      </div>
      <div className="grid gap-6 p-6">
        <div>
          <h4 className="mb-2 text-lg font-medium">Bio</h4>
          <div className="grid gap-2 text-sm text-gray-500 dark:text-gray-400">
            <div>
              <span className="font-medium text-gray-900 dark:text-gray-100">
                Jared Palmer
              </span>
              , 32, San Francisco
            </div>
            <p>
              Jared is a passionate writer and avid reader. He loves exploring
              new ideas and sharing his thoughts with the world.
            </p>
          </div>
        </div>
        <div>
          <h4 className="mb-2 text-lg font-medium">Social</h4>
          <div className="flex items-center gap-4">
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100"
              href="#"
            >
              <TwitterIcon className="h-5 w-5" />
              <span className="sr-only">Twitter</span>
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100"
              href="#"
            >
              <LinkedinIcon className="h-5 w-5" />
              <span className="sr-only">LinkedIn</span>
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100"
              href="#"
            >
              <InstagramIcon className="h-5 w-5" />
              <span className="sr-only">Instagram</span>
            </Link>
          </div>
        </div>
        <div>
          <h4 className="mb-2 text-lg font-medium">Writing Stats</h4>
          <div className="grid grid-cols-3 gap-4 text-sm text-gray-500 dark:text-gray-400">
            <div className="space-y-1">
              <div className="font-medium text-gray-900 dark:text-gray-100">
                142
              </div>
              <p>Published Articles</p>
            </div>
            <div className="space-y-1">
              <div className="font-medium text-gray-900 dark:text-gray-100">
                85,320
              </div>
              <p>Total Words</p>
            </div>
            <div className="space-y-1">
              <div className="font-medium text-gray-900 dark:text-gray-100">
                2,450
              </div>
              <p>Avg. Views</p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
